--CREATE DATABASE expomotos_db;
--USE expomotos_db;
--MAIN REGISTER
CREATE TABLE people(
    entryNumber INT NOT NULL AUTO_INCREMENT,
    completeName VARCHAR(200),
    idNumber VARCHAR(200),
    email VARCHAR(80),
    phoneNumber VARCHAR(200),
    favBrand VARCHAR(20),
    standCount INT DEFAULT 0,
    regDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT peoplePK PRIMARY KEY (entryNumber, idNumber, email)
);

CREATE TABLE yamaha(
    entryNumber INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idNumber VARCHAR(200),
    standRegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE suzuki(
    entryNumber INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idNumber VARCHAR(200),
    standRegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
CREATE TABLE bajaj(
    entryNumber INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idNumber VARCHAR(200),
    standRegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
CREATE TABLE honda(
    entryNumber INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idNumber VARCHAR(200),
    standRegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
CREATE TABLE hero(
    entryNumber INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idNumber VARCHAR(200),
    standRegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
CREATE TABLE auteco(
    entryNumber INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idNumber VARCHAR(200),
    standRegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
CREATE TABLE dreams(
    entryNumber INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idNumber VARCHAR(200),
    standRegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
CREATE TABLE akt(
    entryNumber INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idNumber VARCHAR(200),
    standRegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
CREATE TABLE biker(
    entryNumber INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idNumber VARCHAR(200),
    standRegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE credentials(
    user VARCHAR(200) PRIMARY KEY,
    pass VARCHAR(200),
    contest VARCHAR(200)
);